// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

import type {} from '@useautumn/sdk';

declare module '@useautumn/sdk' {
  // Features
  export const social_credits: Feature;
  export const obsidian_templates: Feature;
  export const quote_expansion: Feature;
  export const json_ld_basic_export: Feature;
  export const thread_briefing: Feature;
  export const cross_platform_parser: Feature;
  export const context_window_safe_mode: Feature;
  export const bulk_json_ld_export: Feature;
  export const markdown_export: Feature;
  export const api_commercial_use: Feature;

  // Plans
  export const free: Plan;
  export const starter: Plan;
  export const pro: Plan;
  export const credit_top_up: Plan;

  // Base types
  export type Feature = import('./autumn.config').Feature;
  export type Plan = import('./autumn.config').Plan;
}
