/**
 * Generate the SDK's types, Effect schemas and error classes from public/openapi.json.
 *
 * The OpenAPI document is the single source: the plain client gets TypeScript
 * types, the Effect client gets Schemas that decode every response, and both
 * get the error catalog. The output is committed, so `--check` fails CI when
 * lib/openapi.ts changed and nobody regenerated the SDK.
 *
 *   bun scripts/build-sdk.ts          regenerate the committed files
 *   bun scripts/build-sdk.ts --check  fail if they are stale (CI)
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

type JsonSchema = {
  $ref?: string
  type?: string | string[]
  enum?: unknown[]
  const?: unknown
  properties?: Record<string, JsonSchema>
  required?: string[]
  additionalProperties?: boolean | JsonSchema
  items?: JsonSchema
  oneOf?: JsonSchema[]
  allOf?: JsonSchema[]
  description?: string
  deprecated?: boolean
}

type Parameter = { name: string, in: string, required?: boolean, description?: string, schema: JsonSchema }
type Operation = { operationId: string, summary?: string, parameters?: Parameter[] }
type CatalogEntry = { status: number, title: string }

const root = fileURLToPath(new URL('..', import.meta.url))
const doc = JSON.parse(readFileSync(resolve(root, 'public/openapi.json'), 'utf8')) as {
  components: { schemas: Record<string, JsonSchema> }
  paths: Record<string, Record<string, Operation>>
  'x-error-catalog': { codes: Record<string, CatalogEntry> }
}

const schemas = doc.components.schemas
const catalog = doc['x-error-catalog'].codes
const BOOLEAN_FLAGS = new Set(['true', '1', 'yes', 'false', '0'])
// The SDK sets `format` itself: JSON for typed calls, Markdown or NDJSON for the string and stream calls.
const SDK_OWNED_PARAMS = new Set(['format'])

const header = '// Generated by scripts/build-sdk.ts from public/openapi.json. Do not edit by hand.\n'
const refName = (ref: string) => ref.slice(ref.lastIndexOf('/') + 1)
const camel = (name: string) => name.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase())
const pascal = (name: string) => camel(name).replace(/^[a-z]/, c => c.toUpperCase())
const key = (name: string) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name))
const literal = (value: unknown) => (typeof value === 'string' ? `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'` : JSON.stringify(value))

function doc_(text: string | undefined, indent: string, deprecated = false): string {
  const lines = (text ?? '').trim().replace(/\*\//g, '*\\/').split('\n').filter(Boolean)
  if (deprecated) lines.push('@deprecated')
  if (!lines.length) return ''
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`
  return `${indent}/**\n${lines.map(line => `${indent} * ${line}`).join('\n')}\n${indent} */\n`
}

const types = (schema: JsonSchema) => (Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [])
const isOpenObject = (schema: JsonSchema) => schema.additionalProperties === undefined || schema.additionalProperties === true

// ---------- plain TypeScript ----------

function tsType(schema: JsonSchema, indent: string): string {
  if (schema.$ref) return refName(schema.$ref)
  if (schema.allOf?.length === 1) return tsType(schema.allOf[0], indent)
  if (schema.oneOf) return schema.oneOf.map(s => tsType(s, indent)).join(' | ')
  if (schema.const !== undefined) return literal(schema.const)
  if (schema.enum) return schema.enum.map(literal).join(' | ')
  const list = types(schema)
  if (!list.length) return schema.properties ? tsObject(schema, indent) : 'unknown'
  return list.map(type => tsPrimitive(type, schema, indent)).join(' | ')
}

function tsPrimitive(type: string, schema: JsonSchema, indent: string): string {
  switch (type) {
    case 'string': return 'string'
    case 'integer':
    case 'number': return 'number'
    case 'boolean': return 'boolean'
    case 'null': return 'null'
    case 'array': return `ReadonlyArray<${schema.items ? tsType(schema.items, indent) : 'unknown'}>`
    case 'object': return tsObject(schema, indent)
    default: throw new Error(`build-sdk: unsupported JSON Schema type '${type}'`)
  }
}

function tsObject(schema: JsonSchema, indent: string): string {
  const inner = `${indent}  `
  const required = new Set(schema.required ?? [])
  const fields = Object.entries(schema.properties ?? {}).map(([name, prop]) =>
    `${doc_(prop.description, inner, prop.deprecated)}${inner}readonly ${key(name)}${required.has(name) ? '' : '?'}: ${tsType(prop, inner)}`)
  const extra = schema.additionalProperties
  if (typeof extra === 'object') fields.push(`${inner}readonly [key: string]: ${tsType(extra, inner)}`)
  else if (isOpenObject(schema)) fields.push(`${inner}readonly [key: string]: unknown`)
  if (!fields.length) return '{}'
  return `{\n${fields.join('\n')}\n${indent}}`
}

function tsDeclaration(name: string, schema: JsonSchema): string {
  const body = tsType({ ...schema, description: undefined }, '')
  const isObject = !schema.oneOf && !schema.$ref && body.startsWith('{')
  return `${doc_(schema.description, '')}${isObject ? `export interface ${name} ${body}` : `export type ${name} = ${body}`}\n`
}

// ---------- operations ----------

type OpParam = { wire: string, name: string, type: string, description?: string, required: boolean }

// `?full=true|1|false|0` style flags read better as booleans; `true` serializes to 'true'.
function paramType(schema: JsonSchema): string {
  if (schema.enum?.length && schema.enum.every(v => typeof v === 'string' && BOOLEAN_FLAGS.has(v))) return 'boolean'
  return tsType(schema, '  ')
}

const v1 = Object.entries(doc.paths)
  .filter(([path]) => path.startsWith('/api/v1/'))
  .flatMap(([path, methods]) => Object.entries(methods)
    .filter(([method]) => method === 'get')
    .map(([, op]) => ({ path, op })))

const operations = v1.map(({ path, op }) => {
  const query: OpParam[] = (op.parameters ?? [])
    .filter(p => p.in === 'query' && !SDK_OWNED_PARAMS.has(p.name))
    .map(p => ({ wire: p.name, name: camel(p.name), type: paramType(p.schema), description: p.description, required: !!p.required }))
  const pathParams = (op.parameters ?? []).filter(p => p.in === 'path').map(p => p.name)
  return { id: op.operationId, summary: op.summary, path, pathParams, query }
})

function renderTypes(): string {
  const out = [header, '/* eslint-disable */\n']
  out.push('// ---- response schemas ----\n')
  for (const [name, schema] of Object.entries(schemas)) out.push(tsDeclaration(name, schema))

  out.push('// ---- request parameters (/api/v1) ----\n')
  for (const op of operations) {
    const fields = op.query.map(p => `${doc_(p.description, '  ')}  readonly ${p.name}${p.required ? '' : '?'}: ${p.type}`)
    out.push(`${doc_(`Query parameters for \`${op.id}\` (${op.path}).`, '')}export interface ${pascal(op.id)}Query {\n${fields.join('\n')}\n}\n`)
  }

  out.push('// ---- operation table: camelCase option -> wire parameter ----\n')
  const table = operations.map(op => {
    const params = op.query.map(p => `      ${key(p.name)}: '${p.wire}',`).join('\n')
    return `  ${op.id}: {\n    path: '${op.path}',\n    pathParams: [${op.pathParams.map(literal).join(', ')}],\n    query: {\n${params}\n    },\n  },`
  })
  out.push(`export const operations = {\n${table.join('\n')}\n} as const\n`)
  out.push('export type OperationId = keyof typeof operations\n')

  out.push('// ---- error catalog ----\n')
  const codes = Object.entries(catalog).map(([code, entry]) => `  ${code}: { status: ${entry.status}, title: ${literal(entry.title)} },`)
  out.push(`${doc_('Every documented problem `code`, with its HTTP status. A 502 or 503 may carry an unlisted provider code; treat it as `upstream_error`.', '')}export const errorCatalog = {\n${codes.join('\n')}\n} as const\n`)
  out.push('export type ErrorCode = keyof typeof errorCatalog\n')
  return out.join('\n')
}

// ---------- Effect Schema ----------

// Schemas that reference themselves (Post.quote) or a schema declared later need Schema.suspend.
const order = Object.keys(schemas)
const declared = new Set<string>()

function fxType(schema: JsonSchema, owner: string, indent = ''): string {
  if (schema.$ref) {
    const name = refName(schema.$ref)
    return declared.has(name) && name !== owner ? name : `Schema.suspend((): Schema.Codec<T.${name}> => ${name})`
  }
  if (schema.allOf?.length === 1) return fxType(schema.allOf[0], owner, indent)
  if (schema.oneOf) return union(schema.oneOf.map(s => fxType(s, owner, indent)))
  if (schema.const !== undefined) return `Schema.Literal(${literal(schema.const)})`
  if (schema.enum) return schema.enum.length === 1 ? `Schema.Literal(${literal(schema.enum[0])})` : `Schema.Literals([${schema.enum.map(literal).join(', ')}])`
  const list = types(schema)
  if (!list.length) return schema.properties ? fxObject(schema, owner, indent) : 'Schema.Unknown'
  return union(list.map(type => fxPrimitive(type, schema, owner, indent)))
}

function union(members: string[]): string {
  if (members.length === 1) return members[0]
  const nonNull = members.filter(m => m !== 'Schema.Null')
  if (nonNull.length === 1) return `Schema.NullOr(${nonNull[0]})`
  return `Schema.Union([${members.join(', ')}])`
}

function fxPrimitive(type: string, schema: JsonSchema, owner: string, indent: string): string {
  switch (type) {
    case 'string': return 'Schema.String'
    // Integers decode as numbers: the API's JSON numbers are the contract, not their integrality.
    case 'integer':
    case 'number': return 'Schema.Number'
    case 'boolean': return 'Schema.Boolean'
    case 'null': return 'Schema.Null'
    case 'array': return `Schema.Array(${schema.items ? fxType(schema.items, owner, indent) : 'Schema.Unknown'})`
    case 'object': return fxObject(schema, owner, indent)
    default: throw new Error(`build-sdk: unsupported JSON Schema type '${type}'`)
  }
}

function fxObject(schema: JsonSchema, owner: string, indent: string): string {
  const inner = `${indent}  `
  const required = new Set(schema.required ?? [])
  const fields = Object.entries(schema.properties ?? {}).map(([name, prop]) => {
    const value = fxType(prop, owner, inner)
    return `${inner}${key(name)}: ${required.has(name) ? value : `Schema.optionalKey(${value})`},`
  })
  const struct = `Schema.Struct({\n${fields.join('\n')}\n${indent}})`
  const extra = schema.additionalProperties
  // Open objects keep their unknown keys; a plain Struct would strip them on decode.
  if (typeof extra === 'object') {
    const record = `Schema.Record(Schema.String, ${fxType(extra, owner, indent)})`
    return fields.length ? `Schema.StructWithRest(${struct}, [${record}])` : record
  }
  if (isOpenObject(schema)) {
    const record = 'Schema.Record(Schema.String, Schema.Unknown)'
    return fields.length ? `Schema.StructWithRest(${struct}, [${record}])` : record
  }
  return struct
}

function renderSchemas(): string {
  const out = [header, "import { Schema } from 'effect'", "import type * as T from '../../generated/types.js'\n"]
  for (const name of order) {
    const body = fxType({ ...schemas[name], description: undefined }, name)
    out.push(`${doc_(schemas[name].description, '')}export const ${name}: Schema.Codec<T.${name}> = ${body}\n`)
    declared.add(name)
  }
  return out.join('\n')
}

// ---------- Effect tagged errors ----------

function renderErrors(): string {
  const out = [header, "import { Data } from 'effect'", "import type { ApiErrorFields } from '../errors.js'\n"]
  const tags = Object.keys(catalog).map(code => ({ code, tag: pascal(code) }))
  for (const { code, tag } of tags) {
    out.push(`${doc_(`\`${code}\` (${catalog[code].status}): ${catalog[code].title}.`, '')}export class ${tag} extends Data.TaggedError('${tag}')<ApiErrorFields> {}\n`)
  }
  out.push(`${doc_('A problem whose `code` is not in the catalog, such as a provider-specific 502.', '')}export class UnknownApiError extends Data.TaggedError('UnknownApiError')<ApiErrorFields> {}\n`)
  out.push(`/** Every error the API can answer with, one tag per catalog code. */\nexport type ApiError =\n${[...tags.map(t => `  | ${t.tag}`), '  | UnknownApiError'].join('\n')}\n`)
  out.push(`export const errorClasses = {\n${tags.map(t => `  ${t.code}: ${t.tag},`).join('\n')}\n} as const\n`)
  return out.join('\n')
}

// ---------- write or check ----------

const outputs = [
  { file: 'packages/sdk/src/generated/types.ts', render: renderTypes },
  { file: 'packages/sdk/src/effect/generated/schemas.ts', render: renderSchemas },
  { file: 'packages/sdk/src/effect/generated/errors.ts', render: renderErrors },
]

const check = process.argv.includes('--check')
let stale = 0
for (const { file, render } of outputs) {
  const target = resolve(root, file)
  const rendered = render()
  let current: string | undefined
  try {
    current = readFileSync(target, 'utf8')
  } catch {
    current = undefined
  }
  const label = relative(root, target)
  if (current === rendered) {
    console.log(`sdk: ${label} is up to date`)
  } else if (check) {
    console.error(`sdk: ${label} is stale. Run \`bun run sdk:build\` and commit the result.`)
    stale++
  } else {
    writeFileSync(target, rendered)
    console.log(`sdk: wrote ${label}`)
  }
}
if (stale) process.exit(1)
